---
#
# Ansible managed
#
repository:
  description: Install and configure mongodb on your system.
  homepage: https://robertdebock.nl/
  topics: mongodb, database, linux, storage, system, tools, ansible, molecule, playbook
